# Generated by Django 4.2.24 on 2025-09-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='name',
            new_name='first',
        ),
    ]
