# Generated by Django 4.2.24 on 2025-09-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_rename_name_passenger_first'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flight',
            new_name='flights',
        ),
    ]
